### ISSUE TITLE
Building distributable for customization not working

### ISSUE THREAD

**Issue by psharkey** [aws-solutions/simple-file-manager-for-amazon-efs#188]
**Describe the bug**
Attempting to build a custom solution but login dialog is never shown. The solution provided in  https://aws.amazon.com/solutions/implementations/simple-file-manager-for-amazon-efs does work but there are no options for customizations. There is a difference with  https://aws.amazon.com/solutions/implementations/simple-file-manager-for-amazon-efs and the version in the mappings is 1.5.0 instead of 1.4.0. Is it possible this repo has not been updated?
```
Mappings:
  Solution:
    Data:
      ID: "SO0145" 
      Version: "v1.5.0"
      AppRegistryApplicationName: "sfm"
      SolutionName: "Simple File Manager for Amazon EFS"
      ApplicationType: "AWS-Solutions"
      AttributeGroupName: "Solution-Metadata"
  SourceCode:
    General:
      GlobalS3Bucket: "solutions-reference"
      RegionalS3Bucket: "solutions"
      CodeKeyPrefix: "simple-file-manager-for-amazon-efs/v1.5.0"
      TemplateKeyPrefix: "simple-file-manager-for-amazon-efs/v1.5.0"
```

**To Reproduce**
Follow steps in https://github.com/aws-solutions/simple-file-manager-for-amazon-efs#building-distributable-for-customization. When browsing to the deployed website the login screen is not shown.
<img width="1219" alt="Screen Shot 2022-12-29 at 8 54 23 AM" src="https://user-images.githubusercontent.com/8724209/209970937-60616b20-e33a-42f7-a594-2b384f1aab63.png">

**Expected behavior**
This should work the same as when deployed using https://aws.amazon.com/solutions/implementations/simple-file-manager-for-amazon-efs/. 
<img width="1162" alt="Screen Shot 2022-12-29 at 9 01 17 AM" src="https://user-images.githubusercontent.com/8724209/209971589-71c92dd2-6593-42aa-8569-6b1fd45d14f8.png">

**Please complete the following information about the solution:**
- [x] Version: [e.g. v1.0.4]

To get the version of the solution, you can look at the description of the created CloudFormation stack. If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "simple-file-manager-for-amazon-efs/v1.0.4"
```

- [x] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [x] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
